### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by starslav** [carykh/jumpcutter#111]
Traceback (most recent call last):
  File "jumpcutter.py", line 4, in <module>
    from audiotsm import phasevocoder
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\audiotsm\__init__.py", line 35, in <module>
    from .ola import ola
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\audiotsm\ola.py", line 8, in <module>
    from audiotsm.base import AnalysisSynthesisTSM, Converter
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\audiotsm\base\__init__.py", line 12, in <module>
    from .analysis_synthesis import AnalysisSynthesisTSM, Converter
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\audiotsm\base\analysis_synthesis.py", line 8, in <module>
    import numpy as np
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\__init__.py", line 12, in <module>
    from ctypes import WinDLL
  File "C:\Users\Komputor\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by starslav** [comment]
I fixed it by re installing ffmpeg

**Comment by Gusted** [comment]
If It's fixed you can close the issue 🤔

**Comment by owoops** [comment]
put a folder where ffmpeg is installed in the PATH variable 

OR

just put ffmpg.exe and the other in the same folder ur in
