### ISSUE TITLE
Subprocess Error

### ISSUE THREAD

**Issue by Levelowel** [carykh/jumpcutter#126]
Traceback (most recent call last): File "C:\Users\Levelowel\Documents\jumpcutter-master\jumpcutter.py", line 167, in <module> rc = subprocess.run(command) File "C:\Users\Levelowel\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 472, in run with Popen(*popenargs, **kwargs) as process: File "C:\Users\Levelowel\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__ restore_signals, start_new_session) File "C:\Users\Levelowel\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child startupinfo) FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by Levelowel** [comment]
I'm using this code: https://github.com/Lamaun/jumpcutter

**Comment by DonaldTsang** [comment]
Oh my god please put the error message in the description not in the title @Levelowel

**Comment by gur111** [comment]
> 
> 
> Oh my god please put the error message in the description not in the title @Levelowel

You mean error logs XD

**Comment by kakol20** [comment]
> I'm using this code: https://github.com/Lamaun/jumpcutter

it still breaks for me when I try to run it (i am on windows 10)

`Traceback (most recent call last):
  File "jumpcutter.py", line 169, in <module>
    rc = subprocess.run(command)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\adria\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Levelowel** [comment]
I can only change the description

**Comment by Levelowel** [comment]
Any ideas yet

**Comment by Lamaun** [comment]
I need more details. Please make your problem easy to reproduce. Feel free to tag me into issues like these. (especially since its my fork)

Have you tried to follow this:
https://github.com/carykh/jumpcutter/issues/114#issuecomment-501682890

**Comment by Levelowel** [comment]
It is working now perfectly. Thanks!
