### ISSUE TITLE
[Errno 2] No such file or directory: 'TEMP/audio.wav'

### ISSUE THREAD

**Issue by FO1R** [carykh/jumpcutter#132]
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "jumpcutter.py", line 109, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Users\pc\AppData\Roaming\Python\Python37\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'

**Comment by Lamaun** [comment]
Please tell us what you did to get this error.

**Comment by FO1R** [comment]
I use Windows 10 64bit system I have all the required software as listed on the required .txt file.
I made a folder with the footage in a .mp4 format and the python script (the python script file wasn't incorrectly copied over because I also tried it with the download version).
Then I held left shift and right clicked on the folders empty space and pressed "Open PowerShell window here" and then typed in "python jumpcutter.py --input_file Female.mp4 --output_file Female_cut.mp4 --sounded_speed 1 --silent_speed 7 --frame_margin 2" then the console spits out the text that is shown in the post.

**Comment by Lamaun** [comment]
Try moving ffmpeg.exe into the same folder as the jumpcutter.py

**Comment by FO1R** [comment]
Thank you, kind sir. the issue was that the ffmpeg.exe was not in the folder but in ShareX>Tools. and you have to have THE .exe and not a shortcut. Got a long video brewing 2 hours after I'm supposed to go to sleep so... Thank you!

**Comment by FO1R** [comment]
Oh, another issue it popped out this "10000 time-altered frames saved.
10020 time-altered frames saved.
10040 time-altered frames saved.
Traceback (most recent call last):
  File "jumpcutter.py", line 166, in <module>
    outputAudioData = np.concatenate((outputAudioData,alteredAudioData/maxAudioVolume))
  File "<__array_function__ internals>", line 6, in concatenate
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (30689280, 2) and data type float64"
don't know what's wrong but i got a temp file full of those save frames and an audio file and then new frames with a tempstart.wav and tempend.wav

**Comment by Lamaun** [comment]
Your memory ran out. Try splitting the video into smaller parts and than using jumpcutter.

**Comment by namitoyokota** [comment]
If you are a macOS user, the problem is most likely that you don't have ffmpeg installed. This can be solved by installing Homebrew and `brew install ffmpeg`. If this is not the problem, the error should also be visible under `/TEMP/params.txt`.

**Comment by SLeAsian** [comment]
> Try moving ffmpeg.exe into the same folder as the jumpcutter.py

I have windows 10 and followed the exact step the author wrote, but I am still getting the exact same error as the post. I can't seem to find the ffmpeg.exe inside the repository and I tried to install it using git install ffmpeg, but the error still persist.

**Comment by Pijussad** [comment]
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "site-packages\scipy\io\wavfile.py", line 233, in read
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
[936] Failed to execute script jumpcutter


I have installed FFmpeg, but still get this part of an error.

**Comment by aminsoheyli** [comment]
> > Try moving ffmpeg.exe into the same folder as the jumpcutter.py
> 
> I have windows 10 and followed the exact step the author wrote, but I am still getting the exact same error as the post. I can't seem to find the ffmpeg.exe inside the repository and I tried to install it using git install ffmpeg, but the error still persist.
> 
> Solution:
> 
> 1. download win64-gpl-4.3.zip from https://github.com/BtbN/FFmpeg-Builds/releases.
> 2. unzip
> 3. copy ffmpeg.exe from bin and paste it into your repository folder

✅ This works fine.
