### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by ArcaPlays** [carykh/jumpcutter#165]
So the instructions I followed were from here: https://github.com/lamaun/jumpcutter/#windows

and this is the error i got `Traceback (most recent call last):
  File "jumpcutter.py", line 13, in <module>
    from pytube import YouTube
  File "C:\Users\Arca\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\Arca\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\Arca\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\Arca\AppData\Local\Programs\Python\Python37\lib\site-packages\pytube\compat.py)`
I looked at some similar issues but i don't seem to understand
I don't know how to fix this so any help would work thx.

**Comment by ArcaPlays** [comment]
wait i think i forgot something

**Comment by Duncluck** [comment]
C:\Users\YOUR_USERNAME_HERE\AppData\Local\Programs\Python\Python37\py pip.exe install pytube --upgrade

you should have pip.exe in your scripts folder

**Comment by Nheyer** [comment]
fixed by pull request #169
