### ISSUE TITLE
HTMLParser Issue

### ISSUE THREAD

**Issue by kiaorapeter** [carykh/jumpcutter#166]
Hi there,
Unfortunately, on running **python jumpcutter.py -h** the following error is occurring;
`C:\Users\wills\Downloads\PyJumpcutterV2-master\PyJumpcutterV2-master>python jumpcutter.py -h
Traceback (most recent call last):
  File "jumpcutter.py", line 9, in <module>
    from pytube import YouTube
  File "C:\Python27\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Python27\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Python27\lib\site-packages\pytube\extract.py", line 6, in <module>
    from html.parser import HTMLParser
ImportError: No module named html.parser`

**Comment by Duncluck** [comment]
try:
C:\Users\wills\AppData\Local\Programs\Python\Python38-32\Scripts>py pip.exe install pytube --upgrade
you should have pip.exe in your scripts folder

**Comment by kiaorapeter** [comment]
Thank you for the quick response. 
I did as instructed (I have a Python37-32 folder not 38-32 - if this is an issue please let me know, I am new to Python). 
I can see pip.exe, pip3.7exe, pip3.exe, pytube.exe, and pytube3.exe in the ..Python37-32\Scripts> folder. 

When I run the command as before the response in the terminal is exactly the same. 
When I run the command **py jumpcutter-master.py -h** I see the following 
`Traceback (most recent call last):
  File "jumpcutter.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`
Just wondering if these two errors are related.

**Comment by callmedougan** [comment]
ok it looks like PIL isnt installed yet - line 2 of the code is asking python to import code from PIL (specifically IMAGE) = there are two things i/we would like you to try/confirm

1_ is pip up to date ? i'd assume if you are as new to this as i am, your copy of python 3.x comes with a variant of PIP (though it might not be latest one) run 
` python -m pip install –upgrade pip ` from the command line - yes i might be teaching you to suck eggs but 2 weeks ago this was all new to me as well (and ive probably made similar blunders)

2) have you installed pytube ? it could be you have but a reasonably simple way is to ask python to install all modules jumpcutter needs to operate (when in the folder with you jumpcutter script there should also be a requirements.txt file ; assuming its there type into the command line
` python3 -m pip install -r requirements.txt ` 
this will instruct python to either (a) install the missing modules (b) verify the modules are already installed

**Comment by kiaorapeter** [comment]
Thank you. Don't worry. I need to suck eggs a little at first. 
After typing command in stage 1, the command states `Requirement already up-to-date: pip in c:\python27\lib\site-packages (20.0.2)` which is nice. 
I didn't know you could just run the requirements.txt file like that so thank you for letting me know. After running **py -m pip install -r requirements.txt** (as starting the command with **python3** did not work, please let me know if this is an issue), the installations occurred and I had the message `Successfully installed Pillow-7.1.1 audiotsm-0.1.2 numpy-1.18.2 scipy-1.4.1`
I did receive some warnings about considering adding certain directories to PATH and to consider upgrading from pip version 10.0.1 to version 20.0.2 (please let me know if this is a big deal). 

I am still getting the HTMLParser issue if I run the command **python jumpcutter.py -h**  
I receive a different issue if I run the command **py jumpcutter.py -h**
Both are shown below. I'm sorry if this is annoying. I don't mind the confusion as I'm still learning. 
`
C:\Users\wills\Downloads\jumpcutter-master>python jumpcutter.py -h
Traceback (most recent call last):
  File "jumpcutter.py", line 13, in <module>
    from pytube import YouTube
  File "C:\Python27\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Python27\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Python27\lib\site-packages\pytube\extract.py", line 6, in <module>
    from html.parser import HTMLParser
ImportError: No module named html.parser

C:\Users\wills\Downloads\jumpcutter-master>py jumpcutter.py -h
Traceback (most recent call last):
  File "jumpcutter.py", line 13, in <module>
    from pytube import YouTube
  File "C:\Users\wills\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\wills\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\wills\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\wills\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\compat.py)`

**Comment by callmedougan** [comment]
It’s times like this I need to find the DM equivalent of github. 

Ok two thjngs from the latest post, it sounds like you have both python2.x and python 3.X installed. Pip has been fully updated on the 2.x edition (up to 20.0.2) but it’s still only on 10.0.1 on your version three python.

Now whether this is a specific or critical factor I will not comment on because I’m too new to this myself, but I would theorise that having two versions of python installed would/could cause conflict.

Ping me back as to what python you have installed, and then we can sort the pytube issue after that
(line 13 in the code, to which I solved by just removing that one line of code as it’s only needed if you are using a YouTube video as your input file) after that

**Comment by kiaorapeter** [comment]
Ah. Thank you so much. I really appreciate the kindness. 
I have Python 2.7.17 installed when I check with the **python -V** command.

**Comment by Poikilos** [comment]
Note that there are at least two situations where you can get `ModuleNotFoundError: No module named 'html.parser'`:

A. You have a file named html.py or a module called html in sys.path (You should rename it). This may be due to having two copies of pip installed, but is often a project-specific issue of having such a file or directory.

B. You are using PyInstaller and one of your modules has imports html.parser but it isn't being analyzed, so PyInstaller doesn't include it in the build. The solution here is to add `import html.parser` (and `import html.entities` for completeness) to your main py file (whatever one is in the first argument of Analyze in your spec file).

I fixed this in my program recently and ran across this issue, so I thought I would help out (my situation was B).

I added the following safeguard in my module to make the error more clear: https://github.com/Hierosoft/hierosoft/commit/d314c4c8bd2ade1fe37186d319f093b76ded05ec

You can also print `dir(html)` when handling the exception to see if it is the real module (It should have the `escape` and `unescape` functions if it is the real module. If not, your situation is A).
