### ISSUE TITLE
OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by jux310** [carykh/jumpcutter#174]
Traceback (most recent call last):
  File "jumpcutter.py", line 108, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Users\Juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\scipy\io\wavfile.py", line 305, in read
    data = _read_data_chunk(fid, format_tag, channels, bit_depth,
  File "C:\Users\Juan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\scipy\io\wavfile.py", line 129, in _read_data_chunk
    data = numpy.frombuffer(fid.read(size), dtype=dtype)
OverflowError: cannot fit 'int' into an index-sized integer

Hi, I don't have much programming experience. If anyone can help me, I'd really appreciate it!!

**Comment by WyattBlue** [comment]
How big is your video? scipy doesn't like audio that's bigger than 2 hours.

**Comment by jux310** [comment]
Thank you for responding
It is 35 minutes long, the video is in 1280 x 720 at 20 frames/s. After the message I have in the program folder a TEMP folder with the frames of the video, a 23 seconds .wav file and a text file called params.txt with the following:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100

**Comment by kubo6472** [comment]
@jux310 just being curious, have you specified the _--frame_rate_ argument? 20FPS is not that common, and it might have caused the trouble. Also, the last line of your response: 

> TEMP/input.mp4: No such file or directory

have you got the file named _input.mp4_?

**Comment by deathlock00** [comment]
> How big is your video? scipy doesn't like audio that's bigger than 2 hours.

I have the same error and my audio is 3h+ long, do you have any idea on how to fix it?
