### ISSUE TITLE
ValueError: Data exceeds wave file size limit

### ISSUE THREAD

**Issue by jessedusty** [carykh/jumpcutter#177]
I guess my lecture was too long lol. Did anyone else come across this?

The source video was 3:23:39, a long Zoom recorded lecture. 

I didn't find anything in my quick search of the issues.

```
212100 time-altered frames saved.
212120 time-altered frames saved.
212140 time-altered frames saved.
Traceback (most recent call last):
  File "/home/jesse/sources/jumpcutter/jumpcutter.py", line 187, in <module>
    wavfile.write(TEMP_FOLDER+"/audioNew.wav",SAMPLE_RATE,outputAudioData)
  File "/home/jesse/.local/lib/python3.8/site-packages/scipy/io/wavfile.py", line 428, in write
    raise ValueError("Data exceeds wave file size limit")
ValueError: Data exceeds wave file size limit
```

**Comment by gusals3587** [comment]
wave file is limited to about 4 GB, check if audioNew.wav is bigger than that ( although I'm a bit doubtful whether that is the case ). On a little tangent, I have a branch of jumpcutter that may be able to deal with bigger files a bit better https://github.com/gusals3587/jumpcutterV2

**Comment by jessedusty** [comment]
@gusals3587 Looks like all the audioNew.wav files were empty (likely the error prevented the files from being written out of from memory and it aborted) 

Wav temp files after several runs failed (each run was in a numbered folder)
```bash
#!/bin/zsh
ls **/*.wav
-rw-r--r-- 1 jesse jesse     0 May  7 02:58 10/TEMP/audioNew.wav
-rw-r--r-- 1 jesse jesse  1.5G May  6 21:04 10/TEMP/audio.wav
-rw-r--r-- 1 jesse jesse  199K May  7 02:58 10/TEMP/tempEnd.wav
-rw-r--r-- 1 jesse jesse 1000K May  7 02:58 10/TEMP/tempStart.wav
-rw-r--r-- 1 jesse jesse     0 May  7 03:10 12/TEMP/audioNew.wav
-rw-r--r-- 1 jesse jesse  1.5G May  6 21:04 12/TEMP/audio.wav
-rw-r--r-- 1 jesse jesse  311K May  7 03:10 12/TEMP/tempEnd.wav
-rw-r--r-- 1 jesse jesse  1.6M May  7 03:10 12/TEMP/tempStart.wav
-rw-r--r-- 1 jesse jesse     0 May  7 03:24 13/TEMP/audioNew.wav
-rw-r--r-- 1 jesse jesse  1.5G May  6 21:03 13/TEMP/audio.wav
-rw-r--r-- 1 jesse jesse  293K May  7 03:24 13/TEMP/tempEnd.wav
-rw-r--r-- 1 jesse jesse  1.5M May  7 03:24 13/TEMP/tempStart.wav
-rw-r--r-- 1 jesse jesse     0 May  7 02:09 8/TEMP/audioNew.wav
-rw-r--r-- 1 jesse jesse  2.1G May  6 21:15 8/TEMP/audio.wav
-rw-r--r-- 1 jesse jesse   84M May  7 02:09 8/TEMP/tempEnd.wav
-rw-r--r-- 1 jesse jesse  419M May  7 02:08 8/TEMP/tempStart.wav
-rw-r--r-- 1 jesse jesse     0 May  7 03:15 9/TEMP/audioNew.wav
-rw-r--r-- 1 jesse jesse  2.1G May  6 21:16 9/TEMP/audio.wav
-rw-r--r-- 1 jesse jesse  651K May  7 03:15 9/TEMP/tempEnd.wav
-rw-r--r-- 1 jesse jesse  3.2M May  7 03:15 9/TEMP/tempStart.wav
```

@gusals3587  I also tried your version but that seems to have it's own issues for my input file, mainly using a ton of RAM (like > 80G) I had to stop it to run out of swap space
