### ISSUE TITLE
Issue with running on Mac

### ISSUE THREAD

**Issue by Epicgamer2469** [carykh/jumpcutter#178]
Whenever I try to run a command it gives this back, I've already installed the libraries so I don't know why it doesn't work.
```
Alexanders-MacBook-Pro:jumpcutter-master alexandertrifiro$ python3 jumpcutter.py -h
Traceback (most recent call last):
  File "jumpcutter.py", line 13, in <module>
    from pytube import YouTube
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pytube/compat.py)

```

**Comment by zPaw** [comment]
You need to install pytube3 instead of pytube.

**Comment by Epicgamer2469** [comment]
Thank you It works fine now!
