### ISSUE TITLE
Script not starting

### ISSUE THREAD

**Issue by chaosflo44-plus** [carykh/jumpcutter#187]
I just wanted to test it out but then this showed up (yes i installed the requirements.txt):
`Traceback (most recent call last):
  File "jumpcutter.py", line 13, in <module>
    from pytube import YouTube
  File "C:\Users\chaos\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "C:\Users\chaos\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\streams.py", line 17, in <module>
    from pytube import extract
  File "C:\Users\chaos\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote' from 'pytube.compat' (C:\Users\chaos\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pytube\compat.py)`

**Comment by zPaw** [comment]
I am fairly certain this is caused by using `pytube` instead of `pytube3`. Try replacing the old version with the new version, and see if that helps.

**Comment by sonich2401** [comment]
I had the same problem and I tried your solution zPaw and it still gives the  same error
