### ISSUE TITLE
I can't run it

### ISSUE THREAD

**Issue by jadosfer** [carykh/jumpcutter#201]
I'm getting this error:

C:\Users\usuario\Documents\Programacion\Python\Python nivel 1>py jumpcutter.py --input_file Arderas.mp4 --output_file Arderascutted.mp4 --silent_speed 999999
"ffmpeg" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"ffmpeg" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Traceback (most recent call last):
  File "C:\Users\usuario\Documents\Programacion\Python\Python nivel 1\jumpcutter.py", line 108, in <module>     
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\Python39\lib\site-packages\scipy\io\wavfile.py", line 639, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'

someone helps me, please

**Comment by bdutta** [comment]
You do not seem to have ffmpeg installed, or if installed your PATH environment variable is not setup correctly. ffmpeg is a dependency of this tool, so first set it up correctly and make sure that you can fun ffmpeg.exe from a cmd window.

**Comment by jadosfer** [comment]
I have resolved it. Thanks!!!
________________________________
De: bdutta ***@***.***>
Enviado: jueves, 10 de junio de 2021 04:03 p. m.
Para: carykh/jumpcutter ***@***.***>
CC: jadosfer ***@***.***>; Author ***@***.***>
Asunto: Re: [carykh/jumpcutter] I can't run it (#201)


You do not seem to have ffmpeg installed, or if installed your PATH environment variable is not setup correctly. ffmpeg is a dependency of this tool, so first set it up correctly and make sure that you can fun ffmpeg.exe from a cmd window.
