### ISSUE TITLE
AssertionError: The TEMP folder may already exist. Delete or rename it, and try again.

### ISSUE THREAD

**Issue by Murilo-Perrone** [carykh/jumpcutter#205]
This is the same issue reported in #79 , which had been closed, but it still happens in the end of file processing. The logs below come from MacOS/Catalina:
```
Traceback (most recent call last):
  File "/Users/adm/Work/jumpcutter/jumpcutter.py", line 93, in <module>
    createPath(TEMP_FOLDER)
  File "/Users/adm/Work/jumpcutter/jumpcutter.py", line 46, in createPath
    assert False, "Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)"
AssertionError: Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)
Traceback (most recent call last):
  File "/Users/adm/Work/jumpcutter/jumpcutter.py", line 44, in createPath
    os.mkdir(s)
FileExistsError: [Errno 17] File exists: 'TEMP'
```

**Comment by John-Henrique** [comment]
You need install ffmpeg and add system variables first.

**Comment by efeakaroz13** [comment]
I did it but i got same error!
