### ISSUE TITLE
Error: no module named PIL

### ISSUE THREAD

**Issue by igorteuri** [carykh/jumpcutter#209]
Hello!

I'm getting this error: 
`Traceback (most recent call last):
  File "D:\Repositórios\jumpcutter-gui\jumpcutter.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
Error! .jumpcutterdone was not found`

Is it a bug or I did something wrong while installing?

**Comment by John-Henrique** [comment]
Voce precisa instalar as dependencias do programa. Faça assim... acesse a pasta onde esta o arquivo requirements.txt e execute estes comandos:

```
pip install -U Pillow; 
pip install -U audiotsm; 
pip install -U scipy; 
pip install -U numpy; 
pip install -U pytube; 
```

Agora tudo deve estar funcioando.

**Comment by GiggyMantis** [comment]
I am also having this issue, in English.
`Traceback (most recent call last):
  File "jumpcutter.py", line 2, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

**Comment by pabloab** [comment]
Might be a noob problem, but even installing dependencies with `pip install -r requirements.txt` I still get `ModuleNotFoundError: No module named 'audiotsm'`, so I just went the `pipx install jumpcutter` way. Then:

```sh
time ionice -c idle nice -n 19 jumpcutter --input "myvideo.mp4" --output "myvideo-$(date -I).mp4"
```
