### ISSUE TITLE
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

### ISSUE THREAD

**Issue by pabloab** [carykh/jumpcutter#214]
Installed with `pipx` over Pop!_OS 22.04 LTS:
```
pipx install jumpcutter                                                                                                      
  installed package jumpcutter 0.1.6, installed using Python 3.10.12
  These apps are now globally available                                                                                                                                                       
    - jumpcutter                            
done! ✨ 🌟 ✨
```
And tried exactly the same way on an Ubuntu 20.04 (working fine). Tried with webm and mp4 with identical results:
```
jumpcutter --input 'my_video.webm' --output 'my_video_(without_silence).webm'

Running with the arguments:
Namespace(input=PosixPath('my_video.webm'), output=PosixPath('my_video_(without_silence).webm'), cut='silent', magnitude_threshold_ratio=0.02, duration_threshold=0.5, failure_tolerance_ratio=0.1, space_on_edges=0.1, silence_part_speed=None, min_loud_part_duration=-1, codec=None, bitrate=None)
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pablo/.local/bin/jumpcutter", line 8, in <module>
    sys.exit(main())
  File "/home/pablo/.local/lib/python3.10/site-packages/jumpcutter/__main__.py", line 115, in main
    clip = Clip(str(input_path), args.min_loud_part_duration, args.silence_part_speed)
  File "/home/pablo/.local/lib/python3.10/site-packages/jumpcutter/clip.py", line 11, in __init__
    self.audio = Audio(self.clip.audio)
  File "/home/pablo/.local/lib/python3.10/site-packages/jumpcutter/clip.py", line 81, in __init__
    self.signal = self.audio.to_soundarray()
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "/home/pablo/.local/lib/python3.10/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/pablo/.local/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 113, in to_soundarray
    return stacker(self.iter_chunks(fps=fps, quantize=quantize,
  File "/home/pablo/.local/lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
  File "/home/pablo/.local/lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
```

**Comment by ptd81** [comment]
I'm having the same issue on Win 10, trying with mkv and mp4 files. But I installed with pip.

Running this command from prompt: jumpcutter --input testfile2.mp4 --output outputfile2.mp4

Running with the arguments:
Namespace(input=WindowsPath('testfile2.mp4'), output=WindowsPath('outputfile2.mp4'), cut='silent', magnitude_threshold_ratio=0.02, duration_threshold=0.5, failure_tolerance_ratio=0.1, space_on_edges=0.1, silence_part_speed=None, min_loud_part_duration=-1, codec=None, bitrate=None)

------------------------------------------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Scripts\jumpcutter.exe\__main__.py", line 7, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\jumpcutter\__main__.py", line 115, in main
    clip = Clip(str(input_path), args.min_loud_part_duration, args.silence_part_speed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\jumpcutter\clip.py", line 11, in __init__
    self.audio = Audio(self.clip.audio)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\jumpcutter\clip.py", line 81, in __init__
    self.signal = self.audio.to_soundarray()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\audio\AudioClip.py", line 113, in to_soundarray
    return stacker(self.iter_chunks(fps=fps, quantize=quantize,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\shape_base.py", line 216, in _vhstack_dispatcher
    return _arrays_for_stack_dispatcher(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\shape_base.py", line 209, in _arrays_for_stack_dispatcher
    raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.

**Comment by lennart-finke** [comment]
For me, what fixed it was wrapping `list()` around `self.iter_chunks` in the file `AudioClip.py` within the `moviepy` package and then manually specifying `codec = 'libx264'` in the file `VideoClip.py` for the same package.
