### ISSUE TITLE
Executable file

### ISSUE THREAD

**Issue by uwuplant** [carykh/jumpcutter#3]
https://drive.google.com/open?id=1U3KNZlUyaImbub4GhmHu2DY8SEDaWyA0 

Hash: 81CB7C1CC4D9B239A82FB65F9F48A8734F3DAECB1ED26A533C2A804D1BADF7D0

**Comment by uwuplant** [comment]
Can set this up on jenkins to automatically build executable, is it worth it?

**Comment by balsoft** [comment]
I can help build a standalone linux executable if needed and set up a travis build for that. Having 2 CI's just building executables is great, isn't it?

**Comment by cthpw103** [comment]
building a freebsd package

**Comment by balsoft** [comment]
This is already better than Premiere and Aftereffects because it has support on all the major platforms!

**Comment by cthpw103** [comment]
i know right :cowboy:

**Comment by cthpw103** [comment]
also: make an installer with ffmpeg in it.

**Comment by balsoft** [comment]
> also: make an installer with ffmpeg in it.

That's exactly what I'm doing ATM.

**Comment by cthpw103** [comment]
should we make a mac os x port?

**Comment by balsoft** [comment]
> should we make a mac os x port?

Consider this in progress.

**Comment by cthpw103** [comment]
and also we should make a GUI for this!

**Comment by kbartek05** [comment]
We could maybe do it with Tkinter? It would be good, cause Tkinter is included with pyInstaller.

**Comment by cthpw103** [comment]
yeah with Tkinter, sounds good

**Comment by balsoft** [comment]
Linux version: https://drive.google.com/file/d/1bL0y_N8o-94nFI26Ct8MrkiiPW3B9IO1/view?usp=sharing

**Comment by balsoft** [comment]
Turns out you need a Mac to build stuff for OSX. Too bad.

**Comment by kbartek05** [comment]
We could make a VM and build it from there, maybe? Possibly? idk, never done anything with OSX

**Comment by balsoft** [comment]
Just to double-check that I'm not trying to `rm -rf` or anything, check out #13 to build it yourself (requires POSIX-like system like Linux, OSX or WSL and nix).

**Comment by balsoft** [comment]
> We could make a VM and build it from there, maybe? Possibly? idk, never done anything with OSX

Yeah, VM with hackintosh might work, too much effort tho.

**Comment by will9183** [comment]
My windows build works with Python 3. I had an issue with the above one looking for Python 2. Here is the link: https://github.com/will9183/jumpcutter/releases/download/v1.0-beta/jumpcutter-win.zip

**Comment by uwuplant** [comment]
Sorry, I use python 2 atm, so my executables won't be compatible with 3.x for now. Will figure out tomorrow.

**Comment by will9183** [comment]
Ya and I think mine doesn't require python to be installed beforehand but ffmpeg. My plan is to make an NSIS installer that does all of this. I have done this in the past.

**Comment by pniedzwiedzinski** [comment]
Docker image might also be a good idea

**Comment by balsoft** [comment]
> Docker image might also be a good idea

I can build a docker image from nix quite easily if needed. Someone please ping me if this would be helpful.

**Comment by nevercast** [comment]
I like the idea of building this on Travis, This keeps the build process open source and transparent.

**Comment by cthpw103** [comment]
this is the only good editing software that works on linux

**Comment by DeflatedPickle** [comment]
@cthpw103 and @kbartek05, since you mentioned it, I made a GUI for the program and I've created a pull request at #35.

**Comment by JettJamez** [comment]
How does this work? I open it and it just kinda closes...

**Comment by balsoft** [comment]
@JettJamez are you talking about Windows version or Linux version?

**Comment by will9183** [comment]
@JettJamez If it is the windows version you have to run it from the command line.

**Comment by will9183** [comment]
I made a very basic installer with @DeflatedPickle GUI: https://github.com/will9183/jumpcutter/releases/download/v1.1-beta/jumpcutter-installer.exe
I'm planning on making a better install interface and an option to install ffmpeg

**Comment by cthpw103** [comment]
i like this progress

**Comment by JettJamez** [comment]
@balsoft and @will9183 thx, sorry i didnt see earlier.

**Comment by will9183** [comment]
New installer with bug fixes from @DeflatedPickle and I and new installer UI: https://github.com/will9183/jumpcutter/releases/download/v1.2-beta/jumpcutter-installer.exe

**Comment by will9183** [comment]
And it seems like it throws some issues when I tested this in a virtual machine. This is the error I get when I click run:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "gui.py", line 77, in run
  File "subprocess.py", line 323, in call
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified`
It seems like an issue with my pyinstaller package not picking up tkinter files. Does anyone with better pyinstaller knowledge know how to fix this?

**Comment by DeflatedPickle** [comment]
@will9183, it's not to do with `tkinter`. You're getting the error because `subprocess` can't find the `jumpcutter.py` file. Try listing the working directory?

**Comment by will9183** [comment]
Here is the directory listing: [listing.txt](https://github.com/carykh/jumpcutter/files/3077440/listing.txt) The only problem is that jumpcutter.py is in there.

**Comment by DeflatedPickle** [comment]
@will9183, but the GUI isn't (unless I missed it). Try adding the `jumpcutter.py` file as a resource for your EXE?

**Comment by will9183** [comment]
So the GUI is in there as jumpcutter-gui.exe and jumpcutter.py is included (this is the command I used: `pyinstaller --add-binary jumpcutter.py;. -n jumpcutter-gui --uac-admin gui.py jumpcutter.py`). So I tied a workaround and tried adding my jumpcutter.exe from my excutable from earier. It doesn't give an error but it throws another error: 
[output.txt](https://github.com/carykh/jumpcutter/files/3077583/output.txt). This error also happens in the executable without the GUI. So I am guessing that there was an issue with scipy not being included in the package?

**Comment by Lamaun** [comment]
For everyone who is searching for Dockerfiles:
To my knowledge there are currently 2 Dockerfile providing forks:
https://github.com/rezemble/jumpcutter
https://github.com/Lamaun/jum pcutter/
