### ISSUE TITLE
Permission denied: 'TEMP/tempStart.wav'

### ISSUE THREAD

**Issue by PatrickMitchellUI** [carykh/jumpcutter#50]
```
Traceback (most recent call last):
  File "jumpcutter.py", line 158, in <module>
    wavfile.write(sFile,SAMPLE_RATE,audioChunk)
  File "C:\Users\Patrick Mitchell\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\io\wavfile.py", line 328, in write
    fid = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'TEMP/tempStart.wav'
```

**Comment by elff1493** [comment]
try ruining as root?

**Comment by NatoBoram** [comment]
Running as root shouldn't be needed for such a tool

**Comment by PatrickMitchellUI** [comment]
tried in an admin power shell, no luck

**Comment by Nikita11790** [comment]
For me it only works when running as root.

This does require root
