### ISSUE TITLE
Temp folder already exists.

### ISSUE THREAD

**Issue by jurassicjordan** [carykh/jumpcutter#55]
I have no idea where this "temp" directory is. heres an image of what my command line said [https://imgur.com/VLpRijp](url)

**Comment by Bottersnike** [comment]
In the same folder as your script, there should be a folder named `TEMP`. This was likely left becuause you killed the script at one point. Either delete this manually or run `rm -rf TEMP/` from the same location as where you are running the script. As an asside, that terminal is horible to read.

**Comment by NoelHVincent** [comment]
I'm having the same issue on Windows:

I get this error before the script even begins processing the video.
I've done everything suggested in the other threads, such as placing the video in the same directory as the py script, installing ffmpeg, etc.
I checked to see whether a TEMP folder has been created. It hadn't.

Maybe it's a permissions issue with os.mkdir()?
Any help would be really appreciated.

Here's the console output:

```
C:\WINDOWS\system32>python D:\DDocuments\jumpcutter-master\jumpcutter.py --input_file whatssohard.mp4 --output_file test1.mp4
Traceback (most recent call last):
  File "D:\DDocuments\jumpcutter-master\jumpcutter.py", line 44, in createPath
    os.mkdir(s)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'TEMP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DDocuments\jumpcutter-master\jumpcutter.py", line 93, in <module>
    createPath(TEMP_FOLDER)
  File "D:\DDocuments\jumpcutter-master\jumpcutter.py", line 46, in createPath
    assert False, "Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)"
AssertionError: Creation of the directory %s failed. (The TEMP folder may already exist. Delete or rename it, and try again.)

C:\WINDOWS\system32>python D:\DDocuments\jumpcutter-master\jumpcutter.py --input_file whatssohard.mp4 --output_file test1.mp4
```

**Comment by jossebul** [comment]
I have the exact same issue as NoelHVincent
