### ISSUE TITLE
Trying to add a NoneType

### ISSUE THREAD

**Issue by GoodClover** [carykh/jumpcutter#57]
I'm not the best at python but by the looks of it TEMP_FOLDER is Nothing/NoneType and that is causing an error. Using Python 3.7
Command: `jumpcutter.py --input_file Mii.mp4 --output_file MiiBut.mp4 --sounded_speed 1 --silent_speed 999999 --frame_margin 0`
`
Traceback (most recent call last):
  File "C:\Users\olive\Documents\Github\jumpcutter\jumpcutter.py", line 188, in <module>
    copyFrame(lastExistingFrame,outputFrame)
  File "C:\Users\olive\Documents\Github\jumpcutter\jumpcutter.py", line 27, in copyFrame
    src = TEMP_FOLDER+"/frame{:06d}".format(inputFrame+1)+".jpg"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
`

**Comment by pniedzwiedzinski** [comment]
I couldn't reproduce the error. It looks like it has trouble with getting content from `TEMP` folder. You could check if this directory exists and what's inside it.

**Comment by justansweringthisonequestion** [comment]
I ran into the same error and found a solution.
In jumpcutter.py modify line 95:
`command = "ffmpeg -i "+INPUT_FILE+" -qscale:v "+str(FRAME_QUALITY)+" "+TEMP_FOLDER+"/frame%06d.jpg -hide_banner"`
into:
`command = "ffmpeg -i "+INPUT_FILE+" -qscale:v "+str(FRAME_QUALITY)+" "+TEMP_FOLDER+"/frame%06d.jpg"`
That is to say, remove the "-hide_banner" bit
