### ISSUE TITLE
Error when processing video

### ISSUE THREAD

**Issue by joelpisme** [carykh/jumpcutter#59]
Hi. Can anyone help explain these errors to me? I already installed everything and got ffmpeg working (the temp folder was created and the individual frame jpegs are in the folder) but near the end there are these errors:

Traceback (most recent call last):
  File "jumpcutter.py", line 162, in <module>
    tsm.run(reader, writer)
  File "/Library/Python/2.7/site-packages/audiotsm/base/tsm.py", line 76, in run
    _, finished = self.write_to(writer)
  File "/Library/Python/2.7/site-packages/audiotsm/base/analysis_synthesis.py", line 240, in write_to
    n = self._out_buffer.write_to(writer)
  File "/Library/Python/2.7/site-packages/audiotsm/utils/cbuffer.py", line 344, in write_to
    n = writer.write(self._data[:, start:end])
  File "/Library/Python/2.7/site-packages/audiotsm/io/wav.py", line 128, in write
    frames = (buffer.T.reshape((-1,)) * 32676).astype(np.int16).tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

**Comment by Bottersnike** [comment]
Can you try running the code on python 3? It feels like it might be an issue with the fact you're using python 2.7.

**Comment by abhiTronix** [comment]
> AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

@joelpisme You're using an old version of `numpy` just update it and the problem will be solved, @Bottersnike this algorithm works with both python 2 and 3.

**Comment by idekwid** [comment]
@abhiTronix How do I update numpy?

**Comment by J0V1K** [comment]
https://stackoverflow.com/questions/28517937/how-can-i-upgrade-numpy

Look into this, it helped me.
I ran:
sudo pip install --ignore-installed numpy
