### ISSUE TITLE
struct.error: 'L' format requires 0 <= number <= 4294967295

### ISSUE THREAD

**Issue by 23571A** [carykh/jumpcutter#60]
Whenever i try to use this, first of all it takes way longer than expected for the silent and sounded speeding up part, after that this stack trace happens

`Traceback (most recent call last):
  File "jumpcutter.py", line 162, in <module>
    tsm.run(reader, writer)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/base/tsm.py", line 76, in run
    _, finished = self.write_to(writer)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/base/analysis_synthesis.py", line 240, in write_to
    n = self._out_buffer.write_to(writer)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/utils/cbuffer.py", line 344, in write_to
    n = writer.write(self._data[:, start:end])
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/io/wav.py", line 129, in write
    self._writer.writeframes(frames)
  File "/home/adam/anaconda3/lib/python3.7/wave.py", line 440, in writeframes
    self._patchheader()
  File "/home/adam/anaconda3/lib/python3.7/wave.py", line 497, in _patchheader
    self._file.write(struct.pack('<L', 36 + self._datawritten))
struct.error: 'L' format requires 0 <= number <= 4294967295

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jumpcutter.py", line 162, in <module>
    tsm.run(reader, writer)
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/io/wav.py", line 138, in __exit__
    self.close()
  File "/home/adam/anaconda3/lib/python3.7/site-packages/audiotsm/io/wav.py", line 118, in close
    self._writer.close()
  File "/home/adam/anaconda3/lib/python3.7/wave.py", line 447, in close
    self._patchheader()
  File "/home/adam/anaconda3/lib/python3.7/wave.py", line 497, in _patchheader
    self._file.write(struct.pack('<L', 36 + self._datawritten))
struct.error: 'L' format requires 0 <= number <= 4294967295`

**Comment by Bottersnike** [comment]
Is this reproducible across mutliple machines, and if so are you able to provide a file that's causing it?

**Comment by 23571A** [comment]
oh wait, it works now... randomly... whatever 
_**Closed**_
