### ISSUE TITLE
error with audiotsm

### ISSUE THREAD

**Issue by programing-monkey** [carykh/jumpcutter#74]
Traceback (most recent call last):
  File "jumpcutter.py", line 162, in <module>
    tsm.run(reader, writer)
  File "/Library/Python/2.7/site-packages/audiotsm/base/tsm.py", line 76, in run
    _, finished = self.write_to(writer)
  File "/Library/Python/2.7/site-packages/audiotsm/base/analysis_synthesis.py", line 240, in write_to
    n = self._out_buffer.write_to(writer)
  File "/Library/Python/2.7/site-packages/audiotsm/utils/cbuffer.py", line 344, in write_to
    n = writer.write(self._data[:, start:end])
  File "/Library/Python/2.7/site-packages/audiotsm/io/wav.py", line 128, in write
    frames = (buffer.T.reshape((-1,)) * 32676).astype(np.int16).tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'

**Comment by programing-monkey** [comment]
sorry I just realized this was alredy posted
