### ISSUE TITLE
I made a version with a bunch of new features, optimized for Windows, and comes in a GUI!

### ISSUE THREAD

**Issue by ThatOneCalculator** [carykh/jumpcutter#97]
Hey CaryKH! I was wondering if you could check out this custom version which I made with is exactly as the title says? I'd love that The GUI was made with Tkinter, and includes File Selection and YouTube input 😄 
https://github.com/ThatOneCalculator/PyJumpcutterV2

**Comment by kbartek05** [comment]
I suggest that you write to him at Discord rather than making an issue 😛

**Comment by ThatOneCalculator** [comment]
Oh, what's the invite?

**Comment by kcomain** [comment]
You stole my job... nvm

**Comment by kcomain** [comment]
You should've pr this

**Comment by ThatOneCalculator** [comment]
What does that mean?

**Comment by kcomain** [comment]
You can make a pull request on Cary's jumpcutter and make your changes gone
real.

**Comment by ThatOneCalculator** [comment]
Oh thanks! I sent him a discord DM but he didn't reply. I'll make sure to
do a pull request!!!

**Comment by ThatOneCalculator** [comment]
Oh should I have made it a fork instead of a new repo?

**Comment by kcomain** [comment]
fork=repo

**Comment by RakuStuff** [comment]
ok, now how i use this better version?

**Comment by ThatOneCalculator** [comment]
Go on my profile and check for PyCutterV2

**Comment by neonfishingrod** [comment]
mr calculator what did i break

```
Expected number for ar but found: -vn
Traceback (most recent call last):
  File "jumpcutter.py", line 131, in <module>
    sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
  File "C:\.......Python37\lib\site-packages\scipy\io\wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
```

**Comment by ThatOneCalculator** [comment]
Hmm. Try deleting the TEMP folder, and then try and put your video in the
folder with the.py file.

**Comment by neonfishingrod** [comment]
yeah, that's how i was running it already

**Comment by ThatOneCalculator** [comment]
Hmm that has never happened before to me. Try force quitting python

**Comment by jojomoore2007** [comment]
> mr calculator what did i break
> 
> ```
> Expected number for ar but found: -vn
> Traceback (most recent call last):
>   File "jumpcutter.py", line 131, in <module>
>     sampleRate, audioData = wavfile.read(TEMP_FOLDER+"/audio.wav")
>   File "C:\.......Python37\lib\site-packages\scipy\io\wavfile.py", line 233, in read
>     fid = open(filename, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'TEMP/audio.wav'
> ```

Ok. I may or may not have found your problem:

TEMP/audio.wav needs to exist, otherwise your system won't find it (because it isn't there.)
Windows has C:\\\*\\, not C:_/_\*_/_

**Comment by ThatOneCalculator** [comment]
Yeah, but in Python you phrase the system files like that because it'll
immediately break if you use C:\. That's why we use C://
